[package]
name = "use_structopt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3", default-features = false }
log = "0.4.14"
env_logger = "0.9.0"
rand = "0.8.4"
